### ISSUE TITLE
Deprecated trait static method calls in RequestPayload

### ISSUE THREAD

**Issue by Floeig** [idanalyzer/id-analyzer-v2-php#1]
PHP 8.2 is showing deprecation warnings when using the library due to static trait method calls. The warnings appear in Docupass Folder

Deprecated function: `Calling static trait method IDAnalyzer2\RequestPayload::QueryParam is deprecated`

Affected files I've verified:
- src/Api/Docupass/LsDocupass.php
- src/Api/Docupass/CreateDocupass.php
- src/Api/Docupass/RmDocupass.php
But I've quickly saw it impact other files too

Suggested fix:
change `RequestPayload::` by `self::` removes the depreciation warnings
```php
 function __construct() {
        $this->initFields([
            RequestPayload::RouteParam("reference", "string", true, null, "Docupass reference ID"),
        ]);
    }
```
To
```php
 function __construct() {
        $this->initFields([
            self::RouteParam("reference", "string", true, null, "Docupass reference ID"),
        ]);
    }
```

thank you

**Comment by marktohark** [comment]
try 1.0.2

**Comment by Floeig** [comment]
Thank you a lot
